<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>server.markhome.mcf.v3_1</groupId>
		<artifactId>server.markhome.mcf.v3_1</artifactId>
		<version>3.1.42-2026091111</version>
	</parent>
<!--
-->
  <modelVersion>4.0.0</modelVersion>

  <name>MCF 3.1 CFLib </name>
  <groupId>cflib</groupId>
  <artifactId>cflib</artifactId>
  <packaging>pom</packaging>
  <url>https://server.markhome.mcf.v3_1.cflib/</url>
  <version>3.1.42-2026091111</version>

  <properties>
    <project.build.outputTimestamp>2026091111</project.build.outputTimestamp>
	<junit-jupiter.version>6.0.1</junit-jupiter.version>
  </properties>

  <profiles>
    <profile>
      <!--
          This is the dev profile, typically used locally with
          "mvn clean install -Pdev".
          It builds the modules shipped in apache-jena binaries
          but does not build these binaries.
          This profile does not build javadoc.
          This profile does not check license headers.
      -->
      <id>dev</id>

      <properties>
        <rat.skip>true</rat.skip>
      </properties>

      <modules>
		<module>mcf-commons-lang3</module>
        <module>mcf-cflib-core</module>
      </modules>

      <build>
        <plugins>
          <!-- For -Pdev :: don't create javadoc. -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <configuration>
              <skip>true</skip>
            </configuration>
          </plugin>
        </plugins>
      </build>

    </profile>

    <profile>
      <!--
          This is the complete profile, it builds everything including 
          any building modules, javadoc and the distribution packages.
      -->
      <id>complete</id>
      <activation>
        <activeByDefault>true</activeByDefault>
        <property>
          <name>profile.complete</name>
          <value>true</value>
        </property>
      </activation>
      <modules>
		<module>commons-lang3</module>
        <module>cflib-core</module>
      </modules>
      <build>
      </build>
    </profile>

  </profiles>

  <dependencyManagement>
    <dependencies>
    </dependencies>
  </dependencyManagement>

  <build>
    <defaultGoal>clean test install</defaultGoal>
    <plugins>
    </plugins>

  </build>

  <reporting>
    <!-- <outputDirectory>${project.build.directory}/site</outputDirectory> -->

    <plugins>

    </plugins>
  </reporting>

</project>
